FROM node:20 AS builder

WORKDIR /app

ARG VITE_API_BASE_URL
ARG VITE_ML_API_URL

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_ML_API_URL=$VITE_ML_API_URL

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# ---- production ----

FROM node:20

WORKDIR /app
RUN npm install -g serve

COPY --from=builder /app/dist ./dist

EXPOSE 5173

CMD ["serve", "-s", "dist", "-l", "tcp://0.0.0.0:5173"]