version: '3.8'

services:

  backend:
    container_name: eldersafe-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  frontend:
    container_name: eldersafe-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_ML_API_URL=${VITE_ML_API_URL}
    ports:
      - "5173:5173"
    restart: always

  ml:
    container_name: eldersafe-ml
    build:
      context: .
      dockerfile: Dockerfile.ml
    ports:
      - "8010:8010"
    restart: always